name: fab_lab_upeu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

    
  # Cliente HTTP
  dio: ^5.4.3

  # Base de datos Local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Programación funcional
  dartz: ^0.10.1

  # Inyección de dependencias
  get_it: ^8.0.0

 
  cupertino_icons: ^1.0.8
  feather_icons: ^1.2.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  bloc: ^8.1.4
  meta: ^1.15.0
  flutter_dash: ^1.0.0
  sizer: ^3.0.3
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoblanco.png
    - assets/images/Icon-header.png
    - assets/images/menu/foto1.png
    - assets/images/menu/foto2.png
    - assets/images/menu/foto3.png
    - assets/images/menu/foto4.png
    - assets/images/menu/foto5.png
    - assets/images/menu/foto6.png
    - assets/images/menu/pago.png
    
     
