name: fab_lab_upeu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

    
  # Cliente HTTP
  dio: ^5.4.3

  # Base de datos Local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Programación funcional
  dartz: ^0.10.1

  # Inyección de dependencias
  get_it: ^8.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  feather_icons: ^1.2.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
